@startuml
actor Salesforce
participant "Mulesoft"
participant "API Gateway"
participant "FHIR Server"

Salesforce -> Mulesoft: searchNeeds(NHI)
Mulesoft -> "API Gateway": searchNeeds(NHI)
"API Gateway" -> "FHIR Server": searchNeeds(NHI)
"FHIR Server" -> "API Gateway": FHIR Bundle with NHI and Needs
"API Gateway" -> Mulesoft: FHIR Bundle with NHI and Needs
Mulesoft -> Mulesoft : transform(FHIR Bundle with NHI and Needs)
Mulesoft -> Salesforce: Send response with Needs

@enduml
